### ISSUE TITLE
Rename CRC Modules with CRC_ prefix to avoid name collision when published to Arduino Libary

### ISSUE THREAD

**Issue by arajoo** [ChicagoRobotics/CRC_Simula#1]
These classes that are part of the CRC_Library should be prefixed the same as all the other modules:

BehaviorTree
DistanceSensor
IR_AnalogDistance
IR_BinaryDistance
Motor
PingDistance

Otherwise, Arduino ide users are more likely to run into name collisions with other libraries.

**Comment by JamieLaing** [comment]
This looks done to me.
